version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.30.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
  - dependency-name: docsify
    versions:
    - 4.12.0
